### ISSUE TITLE
Do Not highlight links

### ISSUE THREAD

**Issue by microcoder** [jupyter-book/jupyterlab-myst#248]
## Description

Do Not highlight links on pages after update jupyterlab to 4.3.0

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
I have updated the CSS styles in style/base.css to ensure links are properly highlighted in the MyST rendered content. This should address the issue of links not being highlighted after updating to JupyterLab 4.3.0.

I also created pull request: https://github.com/jupyter-book/jupyterlab-myst/pull/249


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

**Comment by MordicusEtCubitus** [comment]
I do confirm this bug

I have opened a bug for this issue on jupyter lab : https://github.com/jupyterlab/jupyterlab/issues/17232

~~~
$ jupyter labextension list 
JupyterLab v4.3.4
/home/aliquis/miniforge3/envs/JBook/share/jupyter/labextensions
        jupyterlab-myst v2.4.2 enabled OK (python, jupyterlab_myst)
        jupyterlab-plotly v5.24.1 enabled  X
        jupyterlab_pygments v0.3.0 enabled OK (python, jupyterlab_pygments)
        jupyterlab-jupytext v1.4.3 enabled OK (python, jupytext)
~~~

**Comment by krassowski** [comment]
This is because JupyterLab no longer spills styles to embedding application, which is implemented by pre-pending `.jp-ThemedContainer` class; while this is a good thing it caused a mild breakage in 4.3 because it increased selector specificity. Apologies that we did not pick this one up when testing https://github.com/jupyterlab/jupyterlab/pull/16519 across different extensions.

In JupyterLab links in rendered Markdown are coloured with:

```css
jp-RenderedHTMLCommon a:link {
    text-decoration: none;
    color: var(--jp-content-link-color);
}
```

which has specificity (0,2,1) which overrides the reset rule:

```css
.jp-ThemedContainer a {
    text-decoration: unset;
    color: unset;
}
```

that has specificity: (0,1,1)

While myst does ship with a `color` targeting links:

```css
.myst :where(a):not(:where([class~="not-prose"], [class~="not-prose"] *)) {
  color: var(--jp-content-link-color, #1976d2);
  text-decoration: none;
  font-weight: 400;
}
```

 it is very low specificity (0,1,0) - due to use of `:where` pseudo-selectors - and gets overridden by the `.jp-ThemedContainer a`.

One solution, documented in https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html#jupyterlab-4-2-to-4-3, is to add `.jp-ThemedContainer` in front (or otherwise increase the selector specificity).

We could also discuss changing the selector upstream in JupyterLab, but that would require some benchmarking too (I am not sure what is the cost of `:where`, but certainly there is a very high cost of using `*` at the right hand side.
